-- UPDATING ADMIN CONTROLS FOR GRANULAR PERMISSIONS
-- Adding new financial and departmental permission columns

ALTER TABLE admin_controls 
ADD COLUMN IF NOT EXISTS expenditure_limit NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS perm_student_mgmt BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_report_approval BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_vault_access BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_audit_logs BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS perm_org_master BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS fin_reports_auth BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS statutory_docs_auth BOOLEAN DEFAULT FALSE;

-- Refresh schema cache
NOTIFY pgrst, 'reload schema';
